apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
         securityContext:
        runAsUser: 200
        fsGroup: 200
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: nexus-config
          volumeMounts:
            - name: nexus-storage
              mountPath: /nexus-data
      volumes:
        - name: nexus-storage
          persistentVolumeClaim:
            claimName: nexus-pvc
